services:
  servicemanagementapp:
    container_name: servicemanagementapp-container 
    image: servicemanagementcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssqlserver

  mssqlserver:
    container_name: mssqlserver-container  
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TestPass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  