services:
  servicemanagementapp:
    container_name: servicemanagementapp-container 
    image: servicemanagementcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=.;Database=Service;User=sa;Password=DugaPLUS!72Kazlachev;
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

  